// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function GetById(arg1:number):Promise<data.Task>;

export function NewTask(arg1:string):Promise<void>;
