// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetById(arg1) {
  return window['go']['controller']['TaskController']['GetById'](arg1);
}

export function NewTask(arg1) {
  return window['go']['controller']['TaskController']['NewTask'](arg1);
}
